name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main       # Explicitly checkout the main branch
          fetch-depth: 0  # We need the full history for tags

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "Using version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          # Verify the tag exists
          if ! git tag | grep -q "$VERSION"; then
            echo "Tag v$VERSION does not exist. Available tags:"
            git tag
            exit 1
          fi

      - name: Calculate SHA256
        id: shasum
        run: |
          # Wait for GitHub to process the release
          echo "Waiting for GitHub release to be processed..."
          sleep 10
          
          # Download the tarball
          echo "Downloading source tarball..."
          curl -L -f "https://github.com/${{ github.repository }}/archive/refs/tags/v${{ env.VERSION }}.tar.gz" -o "v${{ env.VERSION }}.tar.gz"
          
          # Calculate SHA256
          SHA256=$(shasum -a 256 "v${{ env.VERSION }}.tar.gz" | awk '{print $1}')
          echo "SHA256: $SHA256"
          echo "SHA256=$SHA256" >> $GITHUB_ENV
          
          # Download the binary for macOS Intel
          echo "Downloading macOS Intel binary..."
          curl -L -f "https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/radio_cli-x86_64-apple-darwin.tar.gz" -o "macos-binary.tar.gz" || echo "Warning: macOS binary not available yet"
          
          if [ -f "macos-binary.tar.gz" ]; then
            MACOS_SHA256=$(shasum -a 256 "macos-binary.tar.gz" | awk '{print $1}')
            echo "macOS binary SHA256: $MACOS_SHA256"
            echo "MACOS_SHA256=$MACOS_SHA256" >> $GITHUB_ENV
          fi

      - name: Update formula
        run: |
          echo "Updating formula with new version and SHA256..."
          
          # Update main source URL and SHA256
          sed -i "s|url \"https://github.com/${{ github.repository }}/archive/refs/tags/v[0-9.]*\.tar\.gz\"|url \"https://github.com/${{ github.repository }}/archive/refs/tags/v${{ env.VERSION }}.tar.gz\"|" Formula/radio-cli.rb
          sed -i "/^  url \"https:/s|sha256 \"[a-f0-9]*\"|sha256 \"${{ env.SHA256 }}\"|" Formula/radio-cli.rb
          
          # Update macOS Intel binary if available
          if [ -n "${{ env.MACOS_SHA256 }}" ]; then
            echo "Updating macOS Intel binary hash..."
            sed -i "s|url \"https://github.com/${{ github.repository }}/releases/download/v[0-9.]*/radio_cli-macos-amd64\"|url \"https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/radio_cli-x86_64-apple-darwin.tar.gz\"|" Formula/radio-cli.rb
            sed -i "/Hardware\.CPU\.intel/,/end/ s|sha256 \"[a-f0-9]*\"|sha256 \"${{ env.MACOS_SHA256 }}\"|" Formula/radio-cli.rb
          fi
          
          # Show diff of changes
          echo "Formula changes:"
          git diff Formula/radio-cli.rb

      - name: Commit and push
        run: |
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            git add Formula/radio-cli.rb
          fi
          
          if ! git diff --staged --quiet; then
            git commit -m "Update formula to v${{ env.VERSION }}"
            
            # Make sure we're on main branch and it's up to date
            git checkout main
            git pull --rebase
            
            # Apply our changes on top if needed
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              if ! git merge-base --is-ancestor HEAD^ main; then
                git cherry-pick HEAD^..HEAD
              fi
            fi
            
            # Push changes
            git push origin main
          else
            echo "No changes to commit"
          fi