name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # We need the full history for tags

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install hub
        run: |
          sudo apt-get update
          sudo apt-get install -y hub

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Calculate SHA256
        id: shasum
        run: |
          curl -L https://github.com/${{ github.repository }}/archive/refs/tags/v${{ env.VERSION }}.tar.gz -o v${{ env.VERSION }}.tar.gz
          SHA256=$(shasum -a 256 v${{ env.VERSION }}.tar.gz | awk '{print $1}')
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Update formula
        run: |
          sed -i "s|url \".*\"|url \"https://github.com/${{ github.repository }}/archive/refs/tags/v${{ env.VERSION }}.tar.gz\"|" Formula/radio-cli.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ env.SHA256 }}\"|" Formula/radio-cli.rb

      - name: Commit and push
        run: |
          git add Formula/radio-cli.rb
          git commit -m "Update formula to v${{ env.VERSION }}"
          git push origin ${GITHUB_REF%%/*}/main